package app

var helpLines = []string{
	"Arrows              Move the cursor",
	"Home / End          First / last file",
	"PgUp / PgDn         Page up / down",
	"Enter               Run command line, or enter directory,",
	"                    run program, open file",
	"Backspace           Parent directory",
	"Control-PgUp        Parent directory",
	"Tab                 Other panel",
	"Insert, Space       Select file and move down",
	"+ / -               Select / unselect files by mask",
	"*                   Invert selection",
	"",
	"F1                  Help",
	"F2, F9              Menu",
	"F3                  View",
	"F4                  Edit",
	"F5                  Copy",
	"F6                  Rename or move",
	"F7                  Make directory",
	"F8                  Move to Trash",
	"Shift-F8            Delete permanently",
	"F10                 Quit",
	"",
	"Alt-F1 / Alt-F2     Left / right drive",
	"Alt-.               Show hidden files",
	"Control-O           Panels on/off",
	"Control-R           Re-read panel",
	"Control-T           Brief / full mode",
	"Control-U           Swap panels",
	"Control-Enter       Put name into command line",
	"  (also Control-J, Esc Enter)",
	"Control-E / X       Previous / next command",
	"Esc                 Clear command line",
	"",
	"Viewer: F2 wrap, F4 hex, F7 search,",
	"Shift-F7 or n next match, Esc close",
	"",
	"Mouse: click selects, double click opens,",
	"wheel scrolls, key bar and menu clickable",
	"",
	"Esc then a key works as Alt (Option) + key:",
	"Esc 1 ... Esc 0 = F1 ... F10, Esc . = Alt-.",
}
